version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    surefire:
      patterns:
        - org.apache.maven.plugins:maven-surefire-plugin
        - org.apache.maven.plugins:maven-failsafe-plugin
        - org.apache.maven.plugins:maven-surefire-report-plugin
  ignore:
    - dependency-name: "jakarta.*:*"
      update-types:
        - "version-update:semver-major"
        - "version-update:semver-minor"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
